Script started on 2017年03月11日 (週六) 11時44分02秒
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m whoami; pwd
pd2vm
/home/pd2vm
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git congif -l[C[1P[1P[1P -lf -li -lg -l
user.email=emilynov14@gmail.com
user.name=emschenn
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m git config -l[K[K[K[K[K[K[K[Klone https://github. com/emschenn/lab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
[01;32mpd2vm@pd2vm-VirtualBox[01;34m ~ $[00m exit

Script done on 2017年03月11日 (週六) 11時45分04秒
